version: '3.7'

services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: myapp-server
    container_name: myapp-node-server
    command: node app.js
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "9000:9000"
    env_file: ./backend/.env
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  client:
    build:
      context: ./frontend/my-app
      dockerfile: Dockerfile
    image: myapp-client
    container_name: myapp-react-client
    command: npm start
    volumes:
      - ./frontend/my-app/:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
  node_modules:
